package de.unistuttgart.stayinsync.transport.dto.Snapshot;

import com.fasterxml.jackson.databind.JsonNode;

/**
 * Data Transfer Object (DTO) representing the result of a transformation
 * execution.
 * <p>
 * A {@code TransformationResultDTO} encapsulates metadata and payloads of a
 * single
 * transformation run, such as its identifiers, validity status, input/output
 * data,
 * and possible error details. It is used across API and persistence layers to
 * store
 * or transmit the outcome of a transformation process.
 * </p>
 *
 * <p>
 * Fields overview:
 * </p>
 * <ul>
 * <li>{@link #transformationId} — numeric identifier of the executed
 * transformation.</li>
 * <li>{@link #jobId} — string identifier of the job that triggered the
 * transformation.</li>
 * <li>{@link #scriptId} — identifier of the transformation script used for
 * execution.</li>
 * <li>{@link #validExecution} — boolean flag indicating if the transformation
 * completed successfully.</li>
 * <li>{@link #sourceData} — JSON representation of the input data provided to
 * the script.</li>
 * <li>{@link #outputData} — JSON representation of the result produced by the
 * script, if any.</li>
 * <li>{@link #errorInfo} — textual information describing an error or stack
 * trace when execution fails.</li>
 * </ul>
 *
 * @author Mohammed-Ammar Hassnou
 */
public class TransformationResultDTO {
    /** Unique numeric identifier of the executed transformation. */
    private Long transformationId;

    /** Identifier of the job that triggered the transformation execution. */
    private String jobId;
    /** Identifier of the script used to perform the transformation. */
    private String scriptId;
    /** Indicates whether the transformation execution completed successfully. */
    private Boolean validExecution;

    /** JSON structure representing the input data passed to the transformation. */
    private JsonNode sourceData; // input JSON
    /**
     * JSON structure representing the output data generated by the transformation.
     */
    private JsonNode outputData; // result JSON (if any)

    /** Error message or stack trace captured when the transformation failed. */
    private String errorInfo;

    /**
     * Get the unique transformation identifier.
     *
     * @return the transformation ID
     */
    public Long getTransformationId() {
        return transformationId;
    }

    /**
     * Set the unique transformation identifier.
     *
     * @param transformationId the transformation ID to assign
     */
    public void setTransformationId(Long transformationId) {
        this.transformationId = transformationId;
    }

    /**
     * Get the identifier of the job that triggered the transformation execution.
     *
     * @return the job identifier
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * Set the identifier of the job that triggered the transformation execution.
     *
     * @param jobId the job identifier to assign
     */
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }

    /**
     * Get the identifier of the script used to perform the transformation.
     *
     * @return the script identifier
     */
    public String getScriptId() {
        return scriptId;
    }

    /**
     * Set the identifier of the script used to perform the transformation.
     *
     * @param scriptId the script identifier to assign
     */
    public void setScriptId(String scriptId) {
        this.scriptId = scriptId;
    }

    /**
     * Check whether the transformation execution completed successfully.
     *
     * @return {@code true} if execution was valid, {@code false} otherwise
     */
    public Boolean getValidExecution() {
        return validExecution;
    }

    /**
     * Set whether the transformation execution completed successfully.
     *
     * @param validExecution {@code true} if execution was valid, {@code false}
     *                       otherwise
     */
    public void setValidExecution(Boolean validExecution) {
        this.validExecution = validExecution;
    }

    /**
     * Get the JSON structure representing the input data passed to the
     * transformation.
     *
     * @return the input data as a {@link JsonNode}
     */
    public JsonNode getSourceData() {
        return sourceData;
    }

    /**
     * Set the JSON structure representing the input data passed to the
     * transformation.
     *
     * @param sourceData the input data as a {@link JsonNode}
     */
    public void setSourceData(JsonNode sourceData) {
        this.sourceData = sourceData;
    }

    /**
     * Get the JSON structure representing the output data generated by the
     * transformation.
     *
     * @return the output data as a {@link JsonNode}
     */
    public JsonNode getOutputData() {
        return outputData;
    }

    /**
     * Set the JSON structure representing the output data generated by the
     * transformation.
     *
     * @param outputData the output data as a {@link JsonNode}
     */
    public void setOutputData(JsonNode outputData) {
        this.outputData = outputData;
    }

    /**
     * Get the error message or stack trace captured when the transformation failed.
     *
     * @return the error information
     */
    public String getErrorInfo() {
        return errorInfo;
    }

    /**
     * Set the error message or stack trace captured when the transformation failed.
     *
     * @param errorInfo the error information to assign
     */
    public void setErrorInfo(String errorInfo) {
        this.errorInfo = errorInfo;
    }

}