/**
 * core-management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Injectable} from '@angular/core';

// @ts-ignore
import {ApiEndpointQueryParamDTO} from '../models/apiEndpointQueryParamDTO';

import {Observable} from 'rxjs/internal/Observable';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';


@Injectable({
  providedIn: 'root'
})
export class ApiEndpointQueryParamResourceService {

  constructor(protected httpClient: HttpClient) {
  }

  /**
   * Returns all the source-system-endpoints for the specified source-system from the database
   * @param endpointId An optional filter parameter to filter results by endpoint id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigEndpointEndpointIdQueryParamGet(endpointId: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<Array<ApiEndpointQueryParamDTO>>;
  public apiConfigEndpointEndpointIdQueryParamGet(endpointId: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<Array<ApiEndpointQueryParamDTO>>>;
  public apiConfigEndpointEndpointIdQueryParamGet(endpointId: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<Array<ApiEndpointQueryParamDTO>>>;
  public apiConfigEndpointEndpointIdQueryParamGet(endpointId: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {


    return this.httpClient.get<Array<ApiEndpointQueryParamDTO>>(`/api/config/endpoint/${endpointId}/query-param`);
  }

  /**
   * Creates a valid query-param for the specified endpoint
   * @param endpointId
   * @param apiEndpointQueryParamDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigEndpointEndpointIdQueryParamPost(endpointId: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigEndpointEndpointIdQueryParamPost(endpointId: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigEndpointEndpointIdQueryParamPost(endpointId: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigEndpointEndpointIdQueryParamPost(endpointId: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.request<any>('post', `/api/config/endpoint/${endpointId}/query-param`,
      {
        body: apiEndpointQueryParamDTO,
      }
    );
  }

  /**
   * Deletes an exiting query-param
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigEndpointQueryParamIdDelete(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigEndpointQueryParamIdDelete(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigEndpointQueryParamIdDelete(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigEndpointQueryParamIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<any>('delete', `/api/config/endpoint/query-param/${id}`);
  }

  /**
   * Returns a query-param for a given identifier
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigEndpointQueryParamIdGet(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<ApiEndpointQueryParamDTO>;
  public apiConfigEndpointQueryParamIdGet(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<ApiEndpointQueryParamDTO>>;
  public apiConfigEndpointQueryParamIdGet(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<ApiEndpointQueryParamDTO>>;
  public apiConfigEndpointQueryParamIdGet(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.get<ApiEndpointQueryParamDTO>(`/api/config/endpoint/query-param/${id}`);
  }

  /**
   * Completely updates an exiting query-param by replacing it with the passed-in query-param
   * @param id
   * @param apiEndpointQueryParamDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigEndpointQueryParamIdPut(id: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigEndpointQueryParamIdPut(id: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigEndpointQueryParamIdPut(id: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigEndpointQueryParamIdPut(id: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.put<any>(`/api/config/endpoint/query-param/${id}`,
      {body: apiEndpointQueryParamDTO,}
    );
  }
}
