/**
 * core-management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Injectable} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';

// @ts-ignore
import {ApiEndpoindQueryParamValueDTO} from '../models/apiEndpoindQueryParamValueDTO';
// @ts-ignore
import {ApiEndpointQueryParamDTO} from '../models/apiEndpointQueryParamDTO';


@Injectable({
  providedIn: 'root'
})
export class ApiEndpointQueryParamValueResourceService {

  constructor(protected httpClient: HttpClient) {
  }

  /**
   * Deletes an exiting query-param
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigRequestConfigurationQueryParamValueIdDelete(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigRequestConfigurationQueryParamValueIdDelete(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigRequestConfigurationQueryParamValueIdDelete(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigRequestConfigurationQueryParamValueIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<any>('delete', `/api/config/request-configuration/query-param-value/${id})}`
    );
  }

  /**
   * Completely updates an exiting query-param-value by replacing it with the passed-in query-param-value
   * @param id
   * @param apiEndpointQueryParamDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigRequestConfigurationQueryParamValueIdPut(id: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigRequestConfigurationQueryParamValueIdPut(id: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigRequestConfigurationQueryParamValueIdPut(id: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigRequestConfigurationQueryParamValueIdPut(id: number, apiEndpointQueryParamDTO: ApiEndpointQueryParamDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<any>('put', `/api/config/request-configuration/query-param-value/${id}`,
      {
        body: apiEndpointQueryParamDTO,
      }
    );
  }

  /**
   * Returns all the query-parameter-values for the specified source-system from the database
   * @param requestConfigId Associated request config
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigRequestConfigurationRequestConfigIdQueryParamValueGet(requestConfigId: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<Array<ApiEndpointQueryParamDTO>>;
  public apiConfigRequestConfigurationRequestConfigIdQueryParamValueGet(requestConfigId: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<Array<ApiEndpointQueryParamDTO>>>;
  public apiConfigRequestConfigurationRequestConfigIdQueryParamValueGet(requestConfigId: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<Array<ApiEndpointQueryParamDTO>>>;
  public apiConfigRequestConfigurationRequestConfigIdQueryParamValueGet(requestConfigId: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.get<Array<ApiEndpointQueryParamDTO>>(`/api/config/request-configuration/${requestConfigId}/query-param-value`);
  }

  /**
   * Creates a valid query-param-value for the specified endpoint
   * @param requestConfigId
   * @param apiEndpoindQueryParamValueDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigRequestConfigurationRequestConfigIdQueryParamValuePost(requestConfigId: number, apiEndpoindQueryParamValueDTO: ApiEndpoindQueryParamValueDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigRequestConfigurationRequestConfigIdQueryParamValuePost(requestConfigId: number, apiEndpoindQueryParamValueDTO: ApiEndpoindQueryParamValueDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigRequestConfigurationRequestConfigIdQueryParamValuePost(requestConfigId: number, apiEndpoindQueryParamValueDTO: ApiEndpoindQueryParamValueDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigRequestConfigurationRequestConfigIdQueryParamValuePost(requestConfigId: number, apiEndpoindQueryParamValueDTO: ApiEndpoindQueryParamValueDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.post(`/api/config/request-configuration/${requestConfigId}/query-param-value`,
      {body: apiEndpoindQueryParamValueDTO}
    );
  }

}
