/**
 * core-management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Injectable} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';

// @ts-ignore
import {ApiHeaderDTO} from '../models/apiHeaderDTO';
// @ts-ignore
import {CreateApiHeaderDTO} from '../models/createApiHeaderDTO';


@Injectable({
  providedIn: 'root'
})
export class ApiHeaderResourceService {

  constructor(protected httpClient: HttpClient) {
  }

  /**
   * Deletes an exiting api-request-header
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSyncSystemRequestHeaderIdDelete(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigSyncSystemRequestHeaderIdDelete(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigSyncSystemRequestHeaderIdDelete(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigSyncSystemRequestHeaderIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<any>('delete', `/api/config/sync-system/request-header/${id}`,
      {}
    );
  }

  /**
   * Returns a api-request-header for a given identifier
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSyncSystemRequestHeaderIdGet(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<ApiHeaderDTO>;
  public apiConfigSyncSystemRequestHeaderIdGet(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<ApiHeaderDTO>>;
  public apiConfigSyncSystemRequestHeaderIdGet(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<ApiHeaderDTO>>;
  public apiConfigSyncSystemRequestHeaderIdGet(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.request<ApiHeaderDTO>('get', `/api/config/sync-system/request-header/${id}`);
  }

  /**
   * Completely updates an exiting api-request-header by replacing it with the passed-in api-request-header
   * @param id
   * @param apiHeaderDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSyncSystemRequestHeaderIdPut(id: number, apiHeaderDTO: ApiHeaderDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigSyncSystemRequestHeaderIdPut(id: number, apiHeaderDTO: ApiHeaderDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigSyncSystemRequestHeaderIdPut(id: number, apiHeaderDTO: ApiHeaderDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigSyncSystemRequestHeaderIdPut(id: number, apiHeaderDTO: ApiHeaderDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<any>('put', `/api/config/sync-system/request-header/${id}`,
      {
        body: apiHeaderDTO,
      }
    );
  }

  /**
   * Returns all the source-system-endpoints for the specified source-system from the database
   * @param syncSystemId An optional filter parameter to filter results by source system id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSyncSystemSyncSystemIdRequestHeaderGet(syncSystemId: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<Array<ApiHeaderDTO>>;
  public apiConfigSyncSystemSyncSystemIdRequestHeaderGet(syncSystemId: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<Array<ApiHeaderDTO>>>;
  public apiConfigSyncSystemSyncSystemIdRequestHeaderGet(syncSystemId: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<Array<ApiHeaderDTO>>>;
  public apiConfigSyncSystemSyncSystemIdRequestHeaderGet(syncSystemId: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {


    return this.httpClient.request<Array<ApiHeaderDTO>>('get', `/api/config/sync-system/${syncSystemId}/request-header`,
    );
  }

  /**
   * Creates a valid api-request-header for the specified source system
   * @param syncSystemId
   * @param createApiHeaderDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSyncSystemSyncSystemIdRequestHeaderPost(syncSystemId: number, createApiHeaderDTO: CreateApiHeaderDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<ApiHeaderDTO> {


    return this.httpClient.post<ApiHeaderDTO>(`/api/config/sync-system/${syncSystemId}/request-header`, createApiHeaderDTO);
  }

}
