/**
 * core-management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Injectable} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';

// @ts-ignore
import {ApiHeaderValueDTO} from '../models/apiHeaderValueDTO';

@Injectable({
  providedIn: 'root'
})
export class ApiHeaderValueResourceService {

  constructor(protected httpClient: HttpClient) {
  }

  /**
   * Returns all the source-system-endpoints for the specified source-system from the database
   * @param requestConfigId An optional filter parameter to filter results by source system id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigRequestConfigurationRequestConfigIdRequestHeaderGet(requestConfigId: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<Array<ApiHeaderValueDTO>>;
  public apiConfigRequestConfigurationRequestConfigIdRequestHeaderGet(requestConfigId: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<Array<ApiHeaderValueDTO>>>;
  public apiConfigRequestConfigurationRequestConfigIdRequestHeaderGet(requestConfigId: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<Array<ApiHeaderValueDTO>>>;
  public apiConfigRequestConfigurationRequestConfigIdRequestHeaderGet(requestConfigId: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {


    return this.httpClient.request<Array<ApiHeaderValueDTO>>('get', `/api/config/request-configuration/${requestConfigId}/request-header`,);
  }

  /**
   * Creates a valid api-request-header for the specified source system
   * @param requestConfigId
   * @param apiHeaderValueDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigRequestConfigurationRequestConfigIdRequestHeaderPost(requestConfigId: number, apiHeaderValueDTO: ApiHeaderValueDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigRequestConfigurationRequestConfigIdRequestHeaderPost(requestConfigId: number, apiHeaderValueDTO: ApiHeaderValueDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigRequestConfigurationRequestConfigIdRequestHeaderPost(requestConfigId: number, apiHeaderValueDTO: ApiHeaderValueDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigRequestConfigurationRequestConfigIdRequestHeaderPost(requestConfigId: number, apiHeaderValueDTO: ApiHeaderValueDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<any>('post', `/api/config/request-configuration/${requestConfigId}/request-header`);
  }

  /**
   * Deletes an exiting api-request-header-value
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigRequestConfigurationRequestHeaderIdDelete(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigRequestConfigurationRequestHeaderIdDelete(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigRequestConfigurationRequestHeaderIdDelete(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigRequestConfigurationRequestHeaderIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.request<any>('delete', `/api/config/request-configuration/request-header/${id}`);
  }

  /**
   * Returns a api-request-header-value for a given identifier
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigRequestConfigurationRequestHeaderIdGet(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<ApiHeaderValueDTO>;
  public apiConfigRequestConfigurationRequestHeaderIdGet(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<ApiHeaderValueDTO>>;
  public apiConfigRequestConfigurationRequestHeaderIdGet(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<ApiHeaderValueDTO>>;
  public apiConfigRequestConfigurationRequestHeaderIdGet(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<ApiHeaderValueDTO>('get', `/api/config/request-configuration/request-header/${id}`
    );
  }

  /**
   * Completely updates an exiting api-request-header-value by replacing it with the passed-in api-request-header-value
   * @param id
   * @param apiHeaderValueDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigRequestConfigurationRequestHeaderIdPut(id: number, apiHeaderValueDTO: ApiHeaderValueDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigRequestConfigurationRequestHeaderIdPut(id: number, apiHeaderValueDTO: ApiHeaderValueDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigRequestConfigurationRequestHeaderIdPut(id: number, apiHeaderValueDTO: ApiHeaderValueDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigRequestConfigurationRequestHeaderIdPut(id: number, apiHeaderValueDTO: ApiHeaderValueDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.request<any>('put', `/api/config/request-configuration/request-header/${id}`,
      {
        body: apiHeaderValueDTO
      }
    );
  }

}
