/**
 * core-management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Injectable} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';

// @ts-ignore
import {CreateRequestConfigurationDTO} from '../models/createRequestConfigurationDTO';
// @ts-ignore
import {GetRequestConfigurationDTO} from '../models/getRequestConfigurationDTO';


@Injectable({
  providedIn: 'root'
})
export class RequestConfigurationResourceService {

  constructor(protected httpClient: HttpClient) {
  }

  /**
   * Returns the api-request-configurations for the specified endpoint from the database
   * @param endpointId An optional filter parameter to filter results by source system id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemEndpointEndpointIdRequestConfigurationGet(endpointId: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<Array<CreateRequestConfigurationDTO>>;
  public apiConfigSourceSystemEndpointEndpointIdRequestConfigurationGet(endpointId: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<Array<CreateRequestConfigurationDTO>>>;
  public apiConfigSourceSystemEndpointEndpointIdRequestConfigurationGet(endpointId: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<Array<CreateRequestConfigurationDTO>>>;
  public apiConfigSourceSystemEndpointEndpointIdRequestConfigurationGet(endpointId: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<Array<CreateRequestConfigurationDTO>>('get', `/api/config/source-system/endpoint/${endpointId}/request-configuration`,
    );
  }

  /**
   * Creates a valid api request configuration for a specified source system endpoint
   * @param endpointId
   * @param createRequestConfigurationDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemEndpointEndpointIdRequestConfigurationPost(endpointId: number, createRequestConfigurationDTO: CreateRequestConfigurationDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigSourceSystemEndpointEndpointIdRequestConfigurationPost(endpointId: number, createRequestConfigurationDTO: CreateRequestConfigurationDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigSourceSystemEndpointEndpointIdRequestConfigurationPost(endpointId: number, createRequestConfigurationDTO: CreateRequestConfigurationDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigSourceSystemEndpointEndpointIdRequestConfigurationPost(endpointId: number, createRequestConfigurationDTO: CreateRequestConfigurationDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<any>('post', `/api/config/source-system/endpoint/${endpointId}/request-configuration`,
      {
        body: createRequestConfigurationDTO,
      }
    );
  }

  /**
   * Deletes an existing api-request-configuration
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemEndpointRequestConfigurationIdDelete(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigSourceSystemEndpointRequestConfigurationIdDelete(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigSourceSystemEndpointRequestConfigurationIdDelete(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigSourceSystemEndpointRequestConfigurationIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<any>('delete', `/api/config/source-system/endpoint/request-configuration/${id}`);
  }

  /**
   * Returns a api-request-configuration for a given identifier
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemEndpointRequestConfigurationIdGet(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<CreateRequestConfigurationDTO>;
  public apiConfigSourceSystemEndpointRequestConfigurationIdGet(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<CreateRequestConfigurationDTO>>;
  public apiConfigSourceSystemEndpointRequestConfigurationIdGet(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<CreateRequestConfigurationDTO>>;
  public apiConfigSourceSystemEndpointRequestConfigurationIdGet(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {


    return this.httpClient.request<CreateRequestConfigurationDTO>('get', `/api/config/source-system/endpoint/request-configuration/${id}`);
  }

  /**
   * Completely updates an existing api-request-configuration by replacing it with the passed-in api-request-configuration
   * @param id
   * @param createRequestConfigurationDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemEndpointRequestConfigurationIdPut(id: number, createRequestConfigurationDTO: CreateRequestConfigurationDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigSourceSystemEndpointRequestConfigurationIdPut(id: number, createRequestConfigurationDTO: CreateRequestConfigurationDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigSourceSystemEndpointRequestConfigurationIdPut(id: number, createRequestConfigurationDTO: CreateRequestConfigurationDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigSourceSystemEndpointRequestConfigurationIdPut(id: number, createRequestConfigurationDTO: CreateRequestConfigurationDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<any>('put', `/api/config/source-system/endpoint/request-configuration/${id}`,
      {
        body: createRequestConfigurationDTO,
      }
    );
  }

  /**
   * Returns all the api-request-configurations for the specified source-system from the database
   * @param sourceSystemId An optional filter parameter to filter results by source system id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemSourceSystemIdRequestConfigurationGet(sourceSystemId: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<Array<GetRequestConfigurationDTO>>;
  public apiConfigSourceSystemSourceSystemIdRequestConfigurationGet(sourceSystemId: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<Array<GetRequestConfigurationDTO>>>;
  public apiConfigSourceSystemSourceSystemIdRequestConfigurationGet(sourceSystemId: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<Array<GetRequestConfigurationDTO>>>;
  public apiConfigSourceSystemSourceSystemIdRequestConfigurationGet(sourceSystemId: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<Array<GetRequestConfigurationDTO>>('get', `/api/config/source-system/${sourceSystemId}/request-configuration`);
  }

}
