/**
 * core-management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Injectable} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';

// @ts-ignore
import {CreateSourceSystemEndpointDTO} from '../models/createSourceSystemEndpointDTO';
// @ts-ignore
import {SourceSystemEndpointDTO} from '../models/sourceSystemEndpointDTO';
// @ts-ignore
import {TypeScriptGenerationRequest} from '../models/typescriptGenerationRequest';
// @ts-ignore
import {TypeScriptGenerationResponse} from '../models/typescriptGenerationResponse';


@Injectable({
  providedIn: 'root'
})
export class SourceSystemEndpointResourceService {
  apiConfigSourceSystemSourceSystemIdRequestConfigurationDelete(configId: number) {
    throw new Error('Method not implemented.');
  }

  constructor(protected httpClient: HttpClient) {
  }

  /**
   * Deletes an exiting source-system-endpoint
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemEndpointIdDelete(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigSourceSystemEndpointIdDelete(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigSourceSystemEndpointIdDelete(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigSourceSystemEndpointIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.request<any>('delete', `/api/config/source-system/endpoint/${id}`,
    );
  }

  /**
   * Returns a source-system-endpoint for a given identifier
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemEndpointIdGet(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<SourceSystemEndpointDTO>;
  public apiConfigSourceSystemEndpointIdGet(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<SourceSystemEndpointDTO>>;
  public apiConfigSourceSystemEndpointIdGet(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<SourceSystemEndpointDTO>>;
  public apiConfigSourceSystemEndpointIdGet(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<SourceSystemEndpointDTO>('get', `/api/config/source-system/endpoint/${id}`,);
  }

  /**
   * Completely updates an exiting source-system-endpoint by replacing it with the passed-in source-system-endpoint
   * @param id
   * @param sourceSystemEndpointDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemEndpointIdPut(id: number, sourceSystemEndpointDTO: SourceSystemEndpointDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigSourceSystemEndpointIdPut(id: number, sourceSystemEndpointDTO: SourceSystemEndpointDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigSourceSystemEndpointIdPut(id: number, sourceSystemEndpointDTO: SourceSystemEndpointDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigSourceSystemEndpointIdPut(id: number, sourceSystemEndpointDTO: SourceSystemEndpointDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.request<any>('put', `/api/config/source-system/endpoint/${id})}`,
    );
  }

  /**
   * Returns all the source-system-endpoints for a specified system from the database
   * @param sourceSystemId The id of the associated source system
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemSourceSystemIdEndpointGet(sourceSystemId: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<Array<SourceSystemEndpointDTO>>;
  public apiConfigSourceSystemSourceSystemIdEndpointGet(sourceSystemId: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<Array<SourceSystemEndpointDTO>>>;
  public apiConfigSourceSystemSourceSystemIdEndpointGet(sourceSystemId: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<Array<SourceSystemEndpointDTO>>>;
  public apiConfigSourceSystemSourceSystemIdEndpointGet(sourceSystemId: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.request<Array<SourceSystemEndpointDTO>>('get', `/api/config/source-system/${sourceSystemId}/endpoint`);
  }

  /**
   * Creates a valid source-system-endpoint
   * @param sourceSystemId
   * @param createSourceSystemEndpointDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemSourceSystemIdEndpointPost(sourceSystemId: number, createSourceSystemEndpointDTO: Array<CreateSourceSystemEndpointDTO>, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigSourceSystemSourceSystemIdEndpointPost(sourceSystemId: number, createSourceSystemEndpointDTO: Array<CreateSourceSystemEndpointDTO>, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigSourceSystemSourceSystemIdEndpointPost(sourceSystemId: number, createSourceSystemEndpointDTO: Array<CreateSourceSystemEndpointDTO>, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigSourceSystemSourceSystemIdEndpointPost(sourceSystemId: number, createSourceSystemEndpointDTO: Array<CreateSourceSystemEndpointDTO>, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.request<any>('post', `/api/config/source-system/${sourceSystemId}/endpoint`,
      {
        body: createSourceSystemEndpointDTO,
      }
    );
  }

  /**
   * Generate TypeScript interface from JSON schema
   * @param endpointId The ID of the endpoint
   * @param request The TypeScript generation request
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public generateTypeScript(endpointId: number, request: TypeScriptGenerationRequest, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<TypeScriptGenerationResponse>;
  public generateTypeScript(endpointId: number, request: TypeScriptGenerationRequest, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<TypeScriptGenerationResponse>>;
  public generateTypeScript(endpointId: number, request: TypeScriptGenerationRequest, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<TypeScriptGenerationResponse>>;
  public generateTypeScript(endpointId: number, request: TypeScriptGenerationRequest, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.request<TypeScriptGenerationResponse>('post', `/api/config/source-system/endpoint/${endpointId}/generate-typescript`,
      {
        body: request,
        context: options?.context,
        observe: observe,
        reportProgress: reportProgress,
        headers: {
          'Content-Type': 'application/json',
          'Accept': options?.httpHeaderAccept || 'application/json'
        }
      }
    );
  }

}
