/**
 * core-management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Injectable} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';

// @ts-ignore
import {CreateSourceSystemDTO} from '../models/createSourceSystemDTO';
// @ts-ignore
import {SourceSystem} from '../models/sourceSystem';
// @ts-ignore
import {SourceSystemDTO} from '../models/sourceSystemDTO';


@Injectable({
  providedIn: 'root'
})
export class SourceSystemResourceService {

  constructor(protected httpClient: HttpClient) {
  }

  /**
   * Returns all source systems
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemGet(observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<Array<SourceSystem>>;
  public apiConfigSourceSystemGet(observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<Array<SourceSystem>>>;
  public apiConfigSourceSystemGet(observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<Array<SourceSystem>>>;
  public apiConfigSourceSystemGet(observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {


    return this.httpClient.request<Array<SourceSystem>>('get', `/api/config/source-system`,);
  }

  /**
   * Deletes a source system by its ID
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemIdDelete(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigSourceSystemIdDelete(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigSourceSystemIdDelete(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigSourceSystemIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {


    return this.httpClient.delete<any>(`/api/config/source-system/${id}`);
  }

  /**
   * Returns a source system by its ID
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemIdGet(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<SourceSystemDTO>;
  public apiConfigSourceSystemIdGet(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<SourceSystemDTO>>;
  public apiConfigSourceSystemIdGet(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<SourceSystemDTO>>;
  public apiConfigSourceSystemIdGet(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {

    return this.httpClient.request<SourceSystemDTO>('get', `/api/config/source-system/${id}`,);
  }

  /**
   * Fully updates an existing source system
   * @param id
   * @param createSourceSystemDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemIdPut(id: number, createSourceSystemDTO: CreateSourceSystemDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<SourceSystemDTO> {
    return this.httpClient.put<SourceSystemDTO>(`/api/config/source-system/${id}`, createSourceSystemDTO);
  }

  /**
   * Creates a new source system
   * @param createSourceSystemDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigSourceSystemPost(createSourceSystemDTO: CreateSourceSystemDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<SourceSystemDTO> {
    return this.httpClient.post<SourceSystemDTO>(`/api/config/source-system`, createSourceSystemDTO);
  }

}
