/**
 * core-management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Injectable} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';

// @ts-ignore
import {TransformationAssemblyDTO} from '../models/transformationAssemblyDTO';
// @ts-ignore
import {TransformationDetailsDTO} from '../models/transformationDetailsDTO';
// @ts-ignore
import {TransformationShellDTO} from '../models/transformationShellDTO';


@Injectable({
  providedIn: 'root'
})
export class TransformationConfigurationService {

  constructor(protected httpClient: HttpClient) {
  }

  /**
   * Returns all transformations
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigTransformationGet(observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<Array<TransformationDetailsDTO>>;
  public apiConfigTransformationGet(observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpResponse<Array<TransformationDetailsDTO>>>;
  public apiConfigTransformationGet(observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<HttpEvent<Array<TransformationDetailsDTO>>>;
  public apiConfigTransformationGet(observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: 'application/json',
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.request<Array<TransformationDetailsDTO>>('get', `/api/config/transformation`,
    );
  }

  /**
   * Deletes an existing transformation
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigTransformationIdDelete(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigTransformationIdDelete(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigTransformationIdDelete(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigTransformationIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {
    return this.httpClient.delete(`/api/config/transformation/${id}`
    );
  }

  /**
   * Returns a transformation for a given identifier
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigTransformationIdGet(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigTransformationIdGet(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigTransformationIdGet(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigTransformationIdGet(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {


    let localVarPath = `/api/config/transformation/${id}`;
    return this.httpClient.request<any>('get', `/api/config/transformation/${id}`);
  }

  /**
   * Assembles a transformation with its related components
   * Updates an existing transformation shell by linking it to a script, rule, and endpoints using their IDs.
   * @param id
   * @param transformationAssemblyDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigTransformationIdPut(id: number, transformationAssemblyDTO: TransformationAssemblyDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigTransformationIdPut(id: number, transformationAssemblyDTO: TransformationAssemblyDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigTransformationIdPut(id: number, transformationAssemblyDTO: TransformationAssemblyDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigTransformationIdPut(id: number, transformationAssemblyDTO: TransformationAssemblyDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {


    return this.httpClient.request<any>('put', `/api/config/transformation/${id}`,
      {
        body: transformationAssemblyDTO,
      }
    );
  }

  /**
   * Creates a new transformation shell
   * Creates the initial transformation object with basic info like name and description. Returns the created object with its new ID.
   * @param transformationShellDTO
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public apiConfigTransformationPost(transformationShellDTO: TransformationShellDTO, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any>;
  public apiConfigTransformationPost(transformationShellDTO: TransformationShellDTO, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpResponse<any>>;
  public apiConfigTransformationPost(transformationShellDTO: TransformationShellDTO, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<HttpEvent<any>>;
  public apiConfigTransformationPost(transformationShellDTO: TransformationShellDTO, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: undefined,
    context?: HttpContext
  }): Observable<any> {


    return this.httpClient.request<any>('post', `/api/config/transformation`,
      {
        body: transformationShellDTO,
      }
    );
  }

}
