{
 "title": "Quarkus Service Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "TransformationId",
    "query": {
     "query": "label_values(script_execution_time_seconds_count,transformationId)"
    }
   },
   {
    "name": "WorkerpodName",
    "query": {
     "query": "label_values(polling_requests_total,pollingNode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Polling Request Anzahl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "polling_requests_total{pollingNode=\"$WorkerpodName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Script",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "script_execution_time_seconds_count{transformationId=\"$TransformationId\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "expr": "http_server_errors_total{job=\"quarkus_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"quarkus_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "targets": [
    {
     "expr": "http_client_requests_seconds_count{job=\"quarkus_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}