{
 "title": "StayInSync Monitoring Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "WorkerpodName",
    "query": "label_values(polling_requests_total,pollingNode)"
   },
   {
    "name": "transformationId",
    "query": {
     "query": "label_values(script_execution_time_seconds_count,transformationId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"quarkus_metrics\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_usage_after_gc{job=\"quarkus_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Polling Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(polling_requests_total{pollingNode=\"$WorkerpodName\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Script Executions per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(script_execution_time_seconds_count{transformationId=\"$transformationId\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{job=\"quarkus_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RabbitMQ Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rabbitmq_connections{name=\"<default>\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"quarkus_metrics\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}