@startuml
'Components'
boundary ConsumerExecutedPollingJob as consumerExecutedPollingJob
boundary ProducerControlSyncJob as controlSyncJob
control PollingNodeManagement as management
actor PollingJobConfigurator as pollingJobConfig
actor PollingJobRessourceUpdater as pollingJobRessourceUpdater
boundary RestRessource as restRessource

'Relations'
activate management
activate pollingJobRessourceUpdater
controlSyncJob ->> management: activateSyncJob()
management ->> pollingJobConfig: configurePollingJob()
activate pollingJobConfig
pollingJobRessourceUpdater ->> pollingJobConfig: timedAccessPollingJob()
pollingJobConfig ->> pollingJobRessourceUpdater: PollingJob.filterConfiguration
deactivate pollingJobConfig
pollingJobRessourceUpdater ->> restRessource: getJson()
activate restRessource
restRessource ->> pollingJobRessourceUpdater: json.data
deactivate restRessource
pollingJobRessourceUpdater ->> pollingJobRessourceUpdater: pollingJob.filterData()
pollingJobRessourceUpdater ->> pollingJobConfig: pollingJob.filterData


@enduml