/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ApiAuthType = {
    None: 'NONE',
    Basic: 'BASIC',
    ApiKey: 'API_KEY'
} as const;
export type ApiAuthType = typeof ApiAuthType[keyof typeof ApiAuthType];

