/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiEndpointQueryParam } from './apiEndpointQueryParam';
import { ApiRequestConfiguration } from './apiRequestConfiguration';


export interface ApiEndpointQueryParamValue { 
    id?: number;
    requestConfiguration?: ApiRequestConfiguration;
    queryParam?: ApiEndpointQueryParam;
    selectedValue?: string;
}

