/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiEndpoindQueryParamValueDTO { 
    id?: number;
    queryParamId?: number;
    paramName?: string;
    paramValue?: string;
}

