/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiEndpointQueryParamType } from './apiEndpointQueryParamType';


export interface ApiEndpointQueryParamDTO { 
    paramName?: string;
    queryParamType?: ApiEndpointQueryParamType;
    id?: number;
    values?: Set<string>;
}
export namespace ApiEndpointQueryParamDTO {
}


