/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiHeader } from './apiHeader';
import { ApiRequestConfiguration } from './apiRequestConfiguration';


export interface ApiHeaderValue { 
    id?: number;
    requestConfiguration?: ApiRequestConfiguration;
    apiHeader?: ApiHeader;
    selectedValue?: string;
}

