/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiEndpointQueryParamValue } from './apiEndpointQueryParamValue';
import { ApiHeaderValue } from './apiHeaderValue';
import { SyncSystemEndpoint } from './syncSystemEndpoint';


export interface ApiRequestConfiguration { 
    id?: number;
    name?: string;
    used?: boolean;
    syncSystemEndpoint?: SyncSystemEndpoint;
    queryParameterValues?: Set<ApiEndpointQueryParamValue>;
    apiRequestHeaders?: Set<ApiHeaderValue>;
}

