/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiAuthType } from './apiAuthType';


/**
 * BASIC auth payload
 */
export interface BasicAuthDTO { 
    username: string;
    password: string;
    authType?: ApiAuthType;
}
export namespace BasicAuthDTO {
}


