/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiAuthType } from './apiAuthType';
import { ApiAuthConfigurationDTO } from './apiAuthConfigurationDTO';


export interface CreateSourceSystemDTO { 
    id?: number;
    name: string;
    apiUrl: string;
    description?: string;
    apiType: string;
    apiAuthType?: ApiAuthType;
    authConfig?: ApiAuthConfigurationDTO;
    openApiSpec?: Blob;
}
export namespace CreateSourceSystemDTO {
}


