/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiRequestHeaderType } from './apiRequestHeaderType';


export interface CreateApiHeaderDTO { 
    headerType?: ApiRequestHeaderType;
    headerName?: string;
}
export namespace CreateApiHeaderDTO {
}


