/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EDCAsset } from './eDCAsset';


export interface EDC { 
    id?: number;
    name?: string;
    url?: string;
    apiKey?: string;
    edcAssets?: Set<EDCAsset>;
}

