/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EDCAccessPolicy } from './eDCAccessPolicy';


export interface EDCAccessPolicyPermission { 
    id?: number;
    edcAccessPolicy?: EDCAccessPolicy;
    action?: string;
    constraintLeftOperand?: string;
    constraintOperator?: string;
    constraintRightOperand?: string;
}

