/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EDCAsset } from './eDCAsset';
import { EDCAccessPolicyPermission } from './eDCAccessPolicyPermission';


export interface EDCAccessPolicy { 
    id?: number;
    accessPolicyPermissions?: Set<EDCAccessPolicyPermission>;
    edcAsset?: EDCAsset;
}

