/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EDCDataAddress { 
    id?: number;
    jsonLDType?: string;
    type?: string;
    baseURL?: string;
    proxyPath?: boolean;
    proxyQueryParams?: boolean;
}

