/**
 * core-management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiRequestParameterMessageDTO } from './apiRequestParameterMessageDTO';
import { ApiHeaderDTO } from './apiHeaderDTO';
import {JobDeploymentStatus} from '../../../shared/components/job-status-tag/job-status-tag.component';


export interface GetRequestConfigurationDTO {
    id: number;
    name: string;
    used?: boolean;
    deploymentStatus?: JobDeploymentStatus;
    pollingIntervallTimeInMs?: number;
    apiRequestHeaders?: Set<ApiHeaderDTO>;
    apiRequestParameters?: Set<ApiRequestParameterMessageDTO>;
}

