/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiRequestParameterMessageDTO } from './apiRequestParameterMessageDTO';
import { ApiHeaderDTO } from './apiHeaderDTO';


export interface GetRequestConfigurationDTO {
    id: number; 
    name: string;
    used?: boolean;
    pollingIntervallTimeInMs?: number;
    apiRequestHeaders?: Set<ApiHeaderDTO>;
    apiRequestParameters?: Set<ApiRequestParameterMessageDTO>;
}

