/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transformation } from './transformation';
import { ApiEndpointQueryParamValue } from './apiEndpointQueryParamValue';
import { SourceSystemEndpoint } from './sourceSystemEndpoint';
import { ApiHeaderValue } from './apiHeaderValue';
import { SourceSystem } from './sourceSystem';
import { SyncSystemEndpoint } from './syncSystemEndpoint';


export interface SourceSystemApiRequestConfiguration { 
    id?: number;
    name?: string;
    used?: boolean;
    syncSystemEndpoint?: SyncSystemEndpoint;
    queryParameterValues?: Set<ApiEndpointQueryParamValue>;
    apiRequestHeaders?: Set<ApiHeaderValue>;
    transformations?: Set<Transformation>;
    sourceSystem?: SourceSystem;
    sourceSystemEndpoint?: SourceSystemEndpoint;
    pollingIntervallTimeInMs?: number;
}

