/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceSystemEndpoint } from './sourceSystemEndpoint';


export interface SourceSystemVariable { 
    id?: number;
    name?: string;
    jsonObjectKey?: string;
    sourceSystemEndpoint?: SourceSystemEndpoint;
}

