
/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SourceSystemEndpointDTO { 
    id?: number;
    sourceSystemId?: number;
    endpointPath: string;
    httpRequestType: string;
    requestBodySchema?: string;
    responseBodySchema?: string;
}

