/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SourceSystemDTO { 
    id?: number;
    name: string;
    apiUrl: string;
    description?: string;
    apiType: string;
    openApiSpec?: string;
}

