/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetSystemEndpoint } from './targetSystemEndpoint';
import { ApiRequestHeaderType } from './apiRequestHeaderType';
import { SyncSystem } from './syncSystem';


export interface TargetSystemApiRequestHeader { 
    id?: number;
    headerName?: string;
    values?: Set<string>;
    headerType?: ApiRequestHeaderType;
    syncSystem?: SyncSystem;
    targetSystemEndpoint?: TargetSystemEndpoint;
}
export namespace TargetSystemApiRequestHeader {
}


