/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetSystemEndpoint } from './targetSystemEndpoint';


export interface TargetSystemApiQueryParam { 
    id?: number;
    targetSystemEndpoint?: TargetSystemEndpoint;
}

