/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetSystemEndpoint } from './targetSystemEndpoint';
import { Transformation } from './transformation';


export interface TargetSystemVariable { 
    id?: number;
    name?: string;
    targetSystemVariableId?: string;
    transformation?: Transformation;
    targetSystemEndpoint?: TargetSystemEndpoint;
}

