/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransformationAssemblyDTO { 
    id?: number;
    syncJobId?: number;
    sourceSystemEndpointIds?: Set<number>;
    targetSystemEndpointId?: number;
    transformationRuleId?: number;
    transformationScriptId?: number;
}

