/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Transformation } from './transformation';


export interface TransformationScript { 
    id?: number;
    name?: string;
    typescriptCode?: string;
    javascriptCode?: string;
    hash?: string;
    transformation?: Transformation;
}

