/**
 * core-management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TargetSystemEndpoint } from './targetSystemEndpoint';
import { SourceSystemVariable } from './sourceSystemVariable';
import { SourceSystemApiRequestConfiguration } from './sourceSystemApiRequestConfiguration';
import { TransformationScript } from './transformationScript';
import { TransformationRule } from './transformationRule';
import { SyncJob } from './syncJob';


export interface Transformation {
    id?: number;
    name?: string;
    description?: string;
    syncJob?: SyncJob;
    transformationScript?: TransformationScript;
    transformationRule?: TransformationRule;
    sourceSystemApiRequestConfigurations?: Set<SourceSystemApiRequestConfiguration>;
    sourceSystemVariables?: Set<SourceSystemVariable>;
    targetSystemEndpoint?: TargetSystemEndpoint;
}

