/**
 * core-management API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransformationScriptDTO } from './transformationScriptDTO';


export interface TransformationDetailsDTO { 
    id?: number;
    name?: string;
    description?: string;
    syncJobId?: number;
    targetSystemEndpointId?: number;
    transformationRuleId?: number;
    script?: TransformationScriptDTO;
}

