apiVersion: v2
name: stay-in-sync-chart
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 16.0.11
  - name: mariadb
    version: 20.5.6
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 16.5.11
    repository: https://charts.bitnami.com/bitnami
  - name: umbrella
    version: 3.6.3
    repository: https://eclipse-tractusx.github.io/charts/dev
  - name: core-management
    version: 1.0.0-SNAPSHOT
    repository: "file://../stay-in-sync-core/core-management/target/helm/kubernetes/core-management"
  - name: core-polling-node
    version: 1.0.0-SNAPSHOT
    repository: "file://../stay-in-sync-core/core-polling-node/target/helm/kubernetes/core-polling-node"
  - name: core-sync-node
    version: 1.0.0-SNAPSHOT
    repository: "file://../stay-in-sync-core/core-sync-node/target/helm/kubernetes/core-sync-node"